# Cloud Build configuration for Vibe Trading AI Agent
# Deploys the MCP server to Cloud Run via CI/CD

steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:latest'
      - '.'
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:latest'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "☁️ Deploying Vibe Trading AI Agent to Cloud Run..."
        
        # Deploy to Cloud Run
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:${SHORT_SHA} \
          --region=${_REGION} \
          --project=${_PROJECT_ID} \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=4Gi \
          --cpu=2 \
          --max-instances=10 \
          --min-instances=0 \
          --timeout=900 \
          --concurrency=1 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=${_PROJECT_ID},GOOGLE_CLOUD_LOCATION=${_REGION},NODE_ENV=production" \
          --set-env-vars="GEMINI_API_KEY=${_GEMINI_API_KEY}" \
          --set-env-vars="PLUSE_API_KEY=${_PLUSE_API_KEY}"
        
        echo "✅ Cloud Run deployment complete"
        
        # Get service URL
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --project=${_PROJECT_ID} \
          --format="value(status.url)")
        
        echo "🌐 Service URL: $${SERVICE_URL}"
        echo ""
        echo "📋 API Endpoints:"
        echo "  Health Check: $${SERVICE_URL}/health"
        echo "  Stock Analysis: $${SERVICE_URL}/analyze"
        echo ""
        echo "📝 Example Usage:"
        echo "  curl -X POST $${SERVICE_URL}/analyze \\"
        echo "    -H 'Content-Type: application/json' \\"
        echo "    -d '{\"ticker\": \"AAPL\"}'"

# Substitution variables
substitutions:
  _PROJECT_ID: ''  # Set this in Cloud Build trigger
  _REGION: 'us-central1'
  _SERVICE_NAME: 'vibe-trading-agent'
  _GEMINI_API_KEY: ''  # Set this in Cloud Build trigger or Secret Manager
  _PLUSE_API_KEY: ''   # Set this in Cloud Build trigger or Secret Manager

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Use high CPU for faster builds
  diskSizeGb: 100
  env:
    - 'DOCKER_BUILDKIT=1'  # Enable BuildKit for faster builds

# Timeout
timeout: '1200s'  # 20 minutes

# Images to store in registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}-repo/${_SERVICE_NAME}:latest'
